models/Catalog.php
<?php

namespace app\models;

use app\components\IcmsHelper;
use yii\behaviors\TimestampBehavior;
use app\models\CatalogCategorie;
use app\models\CatalogGallery;
use yii\helpers\ArrayHelper;

class Catalog extends \app\components\db\ActiveRecordFiles
{

    public $imageFields = [
        'image' => ['catalog', 'catalog']
    ];
    private $_propsCode;
    private $_props;

    public function rules()
    {
        return [
            ['name', 'required', 'message' => 'Введите название', 'on' => ['default']],
            ['alias', 'required', 'message' => 'Введите название', 'on' => ['default']],
            ['alias', 'match', 'pattern' => '/[a-zA-Z0-9_]+$/', 'message' => 'Только латинские буквы и цифры', 'on' => ['default']],
            ['status', 'in', 'range' => [1, 2], 'message' => 'Выберите правильное значение',],
            ['status', 'default', 'value' => 1],
            ['sort', 'default', 'value' => 0],
            ['sort', 'integer', 'message' => 'Введите целое число'],
            ['price', 'integer', 'message' => 'Введите целое число'],
            ['price_old', 'integer', 'message' => 'Введите целое число'],
            [['content', 'title_seo', 'description_seo', 'keywords_seo', 'auto_url', 'is_popular', 'article'], 'safe', 'on' => 'default'],
            ['catalog_categorie_id', 'exist', 'targetClass' => CatalogCategorie::class, 'targetAttribute' => 'id'],
            [
                '!image', 'file',
                'extensions' => ['png', 'jpg', 'gif'], 'wrongExtension' => 'Доступные форматы: {extensions}',
            ],
        ];
    }

    public function scenarios()
    {
        $defaultScenario = parent::scenarios()[self::SCENARIO_DEFAULT];
        return [
            self::SCENARIO_DEFAULT => $defaultScenario,
            'filter' => ['name'],
        ];
    }

    public function getImages()
    {
        return $this->hasMany(CatalogGallery::class, ['catalog_id' => 'id']);
    }

    public function getFeedbacks()
    {
        return $this->hasMany(Feedback::class, ['catalog_id' => 'id']);
    }

    public function getFeedbacksPublic()
    {
        return $this->hasMany(Feedback::class, ['catalog_id' => 'id'])->andWhere(['status' => Feedback::STATUS_ACTIVE]);
    }

    public function getCategorie()
    {
        return $this->hasOne(CatalogCategorie::class, ['id' => 'catalog_categorie_id']);
    }

    public function getPropsValues()
    {
        return $this->hasMany(CatalogProp::class, ['catalog_id' => 'id']);
    }

    public function getSkus()
    {
        return $this->hasMany(CatalogSku::class, ['catalog_id' => 'id']);
    }

    public function getRelatedGoods()
    {
        return $this->hasMany(Catalog::class, ['id' => 'catalog_related_id'])->
                        viaTable('{{%catalog_related}}', ['catalog_id' => 'id']);
    }

    public function getRelatingGoods()
    {
        return $this->hasMany(Catalog::class, ['id' => 'catalog_id'])->
                        viaTable('{{%catalog_related}}', ['catalog_related_id' => 'id']);
    }

    public static function tableName()
    {
        return '{{%catalog}}';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::class
        ];
    }

    /**
     * Получает свойства товара и его <b>код</b> значения
     * @param boolean $refresh - Обновить ли из базы свойства
     * @return \app\components\properties\Props - модель alias->code
     */
    public function getPropsCode($refresh = false)
    {
        if (!empty($this->_propsCode) && !$refresh) {
            return $this->_propsCode;
        }

        $props_cat = $this->getProperties();

        $props = new \app\components\properties\Props();
        if (count($props_cat) > 0) {
            foreach ($props_cat as $value) {
                $result = null;
                $result_props = CatalogProp::find()->andWhere(['catalog_id' => $this->id, 'props_id' => $value->id])->all();
                if (!is_null($result_props)) {
                    if (($value->prop_type_list_id == 2) && ($value->prop_type_id == 4)) {
                        $result = ArrayHelper::map($result_props, 'id', 'value');
                    } else {
                        $result = ArrayHelper::map($result_props, 'id', 'value');
                        $result = array_shift($result);
                    }
                }
                $props->defineAttribute($value->alias, $result);
                $group = $value->group;
                if (!is_null($group)) {
                    $props->groups->addToGroup($group->alias, $value->alias, $group->name);
                }
                if ($value->is_most == 1) {
                    $props->addRule($value->alias, 'required');
                }
                if ($value->prop_type_id == 2) {
                    $props->addRule($value->alias, 'number', ['integerOnly' => true]);
                }
                if ($value->prop_type_id == 3) {
                    $props->addRule($value->alias, 'number');
                }
                $props->addRule($value->alias, 'safe');
            }
        }
        $this->_propsCode = $props;
        return $props;
    }

    /**
     * Получает свойства товара и его <b>значение</b>
     * @param boolean $refresh - Обновить ли из базы свойства
     * @return \app\components\properties\Props - модель alias->code
     */
    public function getProps($refresh = false)
    {
        if (!empty($this->_props) && !$refresh) {
            return $this->_props;
        }

        $props_cat = $this->getProperties();

        $props = new \app\components\properties\Props();
        if (count($props_cat) > 0) {
            foreach ($props_cat as $value) {
                $result = null;
                $result_props = CatalogProp::find()->andWhere(['catalog_id' => $this->id, 'props_id' => $value->id])->all();
                if (!is_null($result_props)) {
                    switch ($value->prop_type_id) {
                        case 1:
                        case 2:
                        case 3:
                            if (isset($result_props[0])) {
                                $result = $result_props[0]->value;
                            } else {
                                $result = null;
                            }
                            break;
                        case 4:
                            $valuesCodes = ArrayHelper::map($result_props, 'id', 'value');
                            $valuesQuery = PropsValue::find()->andWhere(['in', 'id', $valuesCodes])->orderBy('sort');
                            if ($value->prop_type_list_id == 2) {
                                $values = $valuesQuery->all();
                                $result = ArrayHelper::map($values, 'id', 'name');
                            } else {
                                $values = $valuesQuery->one();
                                if (!is_null($values)) {
                                    $result = $values->name;
                                }
                            }
                            break;
                        case 7:
                            if (isset($result_props[0])) {
                                $result = $result_props[0]->value == 1;
                            } else {
                                $result = null;
                            }
                            break;
                    }
                }
                if (empty($result)) {
                    continue;
                }
                $props->defineAttribute($value->alias, $result);
                $group = $value->group;
                if (!is_null($group)) {
                    $props->groups->addToGroup($group->alias, $value->alias, $group->name);
                }
            }
        }
        $this->_props = $props;
        return $props;
    }

    public function getProperties($get_sku = false)
    {
        $all_parent = \app\components\IcmsHelper::getAllParents(CatalogCategorie::findOne($this->catalog_categorie_id), 'pid');
        $props_codes = \yii\helpers\ArrayHelper::map(CatalogCategorieProp::find()->andWhere(['in', 'catalog_categorie_id', array_keys($all_parent)])->all(), 'props_id', 'props_id');
        return \app\models\Prop::find()->andWhere(['in', 'id', array_keys($props_codes)])->andWhere(['is_sku' => $get_sku])->all();
    }

    public function getSkuList($skuId = null)
    {
        $props_cat = $this->getProperties(true);
        $props = new \app\components\properties\Sku();
        if (count($props_cat) > 0) {
            foreach ($props_cat as $value) {
                $result = null;
                if (!is_null($skuId)) {
                    $result_props = CatalogSkuPropsValue::find()->andWhere(['catalog_sku_id' => $skuId, 'props_id' => $value->id])->all();
                    if (!is_null($result_props)) {
                        if (($value->prop_type_list_id == 2) && ($value->prop_type_id == 4)) {
                            $result = \yii\helpers\ArrayHelper::map($result_props, 'id', 'value');
                        } else {
                            $result = \yii\helpers\ArrayHelper::map($result_props, 'id', 'value');
                            $result = array_shift($result);
                        }
                    }
                }

                $props->defineAttribute($value->alias, $result);
                $group = $value->group;
                if (!is_null($group)) {
                    $props->groups->addToGroup($group->alias, $value->alias, $group->name);
                }
                if ($value->is_most == 1) {
                    $props->addRule($value->alias, 'required');
                }
                if ($value->prop_type_id == 2) {
                    $props->addRule($value->alias, 'number', ['integerOnly' => true]);
                }
                if ($value->prop_type_id == 3) {

views/site/catalog_categories.php
<?php
/* @var $this app\components\View */
?>

<section class="col-sm-12 col-md-12 col-lg-12 content-center">
    <?= \app\widgets\coolbaby\SliderCategories::widget(['sliderId' => 3]) ?>
    <div class="divider divider-lg">
    </div>
    <h1><?= $this->h1 ?></h1>
    <!-- Description -->
    <?= $this->tree->getContent() ?>
    <!-- //end Description -->
    <div class="divider-sm"></div>
    <!-- Categories -->
    <div class="row">
        <?php foreach ($categories as $categorie) { ?>
            <div class="col-xs-6 col-sm-3">
                <div class="category">
                    <a href="<?= yii\helpers\Url::to(['site/catalog_categorie', 'catalog_categorie_alias' => $categorie->alias]) ?>">
                        <img src="<?= $categorie->getPath('image') ?>" alt="">
                    </a>
                    <h4>
                        <a href="<?= yii\helpers\Url::to(['site/catalog_categorie', 'catalog_categorie_alias' => $categorie->alias]) ?>"><?= $categorie->name ?></a>
                    </h4>
                </div>
            </div>
        <?php } ?>
    </div>
    <!-- //end Categories -->
    <div class="divider-sm"></div>
</section>

views/site/catalog_element.php
<?php
/* @var $this app\components\View */

use yii\widgets\Breadcrumbs;
?>
<section class="breadcrumbs">
    <?= Breadcrumbs::widget(
        [
            'links' => \Yii::$app->controller->bread,
            'activeItemTemplate' => '{link}',
            'options' => ['class' => 'container'],
            'itemTemplate' => '{link}<span class="divider">&nbsp;</span>',
            'tag' => 'div'
        ]
    ) ?>
</section>

<!-- Product view -->
<div class="container">
    <div class="product-view row">
        <div class="col-sm-6 col-md-6 col-lg-4">
            <div class="single-product">
                <?php if (!empty($catalog->image)) { ?>
                    <div class="carousel-item">
                        <img class="cloudzoom" src="<?= $catalog->getResizePath('image', 390, 525) ?>" data-cloudzoom="zoomImage: '<?= $catalog->getPath('image') ?>', autoInside : 991, zoomSizeMode: 'image'" alt="<?= $catalog->name ?>"/>
                    </div>
                <?php } ?>
                <?php foreach ($catalog->images as $pic) { ?>
                <div class="carousel-item">
                    <img class="cloudzoom" src="<?= $pic->getResizePath('image', 390, 525) ?>" data-cloudzoom="zoomImage: '<?= $pic->getPath('image') ?>', autoInside : 991, zoomSizeMode: 'image'" alt="<?= $pic->name ?>"/>
                </div>
                <?php } ?>
            </div>
            <div class="wrapper">
                <div class="slider-nav-simple">
                    <?php if (!empty($catalog->image)) { ?>
                        <div class="carousel-item">
                            <img src="<?= $catalog->getPath('image') ?>" alt="<?= $catalog->name ?>">
                        </div>
                    <?php } ?>
                    <?php foreach ($catalog->images as $pic) { ?>
                        <div class="carousel-item">
                            <img src="<?= $pic->getPath('image') ?>" alt="<?= $pic->name ?>">
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="clearfix visible-xs">
        </div>
        <div class="col-sm-6 col-md-6 col-lg-8">
            <h2><?= $catalog->name ?></h2>
            
            <?php if (!empty($catalog->old_price)) { ?>
                <span class="price old"><?= $catalog->old_price ?> р.</span>
            <?php } ?>
            <span class="price new"><?= $catalog->price ?> р.</span>
            <?php if (!empty($catalog->article)) { ?>
                <p>
                    <span><strong>Артикул: </strong></span> <span><?= $catalog->article ?></span>
                </p>
            <?php } ?>
            <div class="divider divider-sm">
            </div>
            <div class="line-divider">
            </div>
            <div class="divider divider-md">
            </div>
            <?php if ($catalogHasSku) { ?>
                <?php foreach ($skuGrid as $key => $value) {
                    ?>
                    <h3 class="shop-product-title"><?= $propsListId[$key] ?></h3>
                    <div class="product-options">
                        <?php foreach ($value as $key2 => $elem) { ?>
                            <input data-catalog-id="<?= $catalog->id ?>" class="get-sku" hidden type="radio" data-prop="<?= $key ?>" value="<?= $key2 ?>" id="prop-<?= $key2 ?>" name="prop-<?= $key ?>">
                            <label for="prop-<?= $key2 ?>" class="icon icon-size">
                                <?= $elem ?>
                            </label>
                        <?php } ?>
                    </div>
                    <?php
                }
            }
            ?>
                    
            <div class="form-inputs">
                <label>Количество:</label>
                <input type='text' data-catalog-id="<?= $catalog->id ?>" class="form-control input-quantity quantity-field" value="1" id='quantity-field-<?= $catalog->id ?>' />
                <?php if ($catalogHasSku) { ?>
                    <input type="hidden" id="product-sku-id-<?= $catalog->id ?>" value=""/>
                <?php } ?>
                <button data-id="<?= $catalog->id ?>" class="btn btn-cool btn-lg basket-add-item" type="submit"><i class="icon flaticon-shopping66"></i>В корзину</button>
            </div>
            <div class="divider divider-md">
            </div>
        </div>
    </div>
    <!-- //end Product view -->
    <!-- Tabs -->
    <section class="producttab">
        <ul class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#tab-1">Описание</a></li>
            <li><a data-toggle="tab" href="#tab-2">Отзывы (<?= count($catalog->feedbacksPublic) ?>)</a></li>
        </ul>
        <div class="tab-content">
            <div id="tab-1" class="tab-pane fade active in">
                <?= $catalog->content ?>

                <h3 class="heading-md margin-bottom-20">Свойства</h3>
                <?php foreach ($catalog->props as $prop_alias => $prop) { ?>
                    <?= $propsList[$prop_alias] ?>:
                    <span>
                    <?php
                    if (!is_array($prop)) {
                        echo $prop;
                    } else {
                        echo implode(", ", $prop);
                    }
                    ?></span><br>
                <?php } ?>
            </div>
            <div id="tab-2" class="tab-pane fade">
                <?php foreach ($catalog->feedbacksPublic as $feed) { ?>
                    <div class="comments">
                        <div class="comment">
                            <div class="inside">
                                <p>
                                    <strong><?= $feed->user->name ?></strong><br>
                                    <?= \app\components\IcmsHelper::dateTimeFormat('Q d, Y H:i', $feed->g_date) ?>
                                </p>
                                <p><?= $feed->content ?></p>
                            </div>
                        </div>
                    </div>
                <?php } ?>
                <div class="divider divider-sm"></div>
                <div class="line-divider"></div>
                <div class="divider divider-sm"></div>
                <div class="row">
                    <div class="col-sm-12">
                    <?php if (!Yii::$app->user->isGuest) { ?>
                        <h3 class="heading-md margin-bottom-30">Добавить отзыв о товаре</h3>
                        <form method="post" class="catalog-feedback-form sky-form sky-changes-4" id="sky-form3">
                            <fieldset>
                                <div class="margin-bottom-30">
                                    <textarea placeholder="Отзыв" class="form-control" name="message" cols="1" rows="6" id="catalog-feedback-form-message"></textarea>
                                </div>
                            </fieldset>
                            <footer class="review-submit">
                                <button class="button btn-cool sendCatalogFeedback" type="submit"><span class="icon flaticon-star129"></span>Отправить</button>
                            </footer>
                        </form>
                    <?php } else { ?>
                        <p>Только авторизованные пользователи могут оставлять отзывы о товарах</p>
                    <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>


<?php if ($catalog->getRelatedGoods()->exists()) { ?>
    <section class="container content slider-products">
        <div class="dotted-line right-space">
        </div>
        <!-- Products list -->
        <div class="pull-left vertical_title_outer right-space">
            <div>
                <span>Сопутствующие товары</span>
            </div>
        </div>
        <div class="pull-left carousel_outer">
            <div class="product-carousel">
                <?php foreach ($catalog->getRelatedGoods()->andWhere(['status' => $catalog::STATUS_ACTIVE])->orderBy(['sort' => SORT_ASC])->each() as $relatedGood) {
                    $categorie = $relatedGood->categorie;
                    ?>
                    <div class="carousel-item">
                        <div class="product-preview">
                            <div class="preview-image-outer">
                                <a href="<?= \yii\helpers\Url::to([
                                    'site/catalog',
                                    'catalog_categorie_alias' => $categorie->alias,
                                    'catalog_id' => $relatedGood->id,
                                    'catalog_alias' => $relatedGood->alias,
                                ]) ?>" class="preview-image">
                                    <?php if (!empty($relatedGood->image)) { ?>
                                        <img class="img-responsive img-default" src="<?= $relatedGood->getPath('image') ?>" alt="<?= $relatedGood->name ?>">
                                    <?php } ?>
                                </a>
                            </div>
                            <h3 class="title"><a href="<?= \yii\helpers\Url::to([
                                    'site/catalog',
                                    'catalog_categorie_alias' => $categorie->alias,
                                    'catalog_id' => $relatedGood->id,
                                    'catalog_alias' => $relatedGood->alias,
                                ]) ?>"><?= $relatedGood->name ?></a></h3>
                            <span class="price new"><?= $relatedGood->price ?> р.</span>
                            <?php if (!empty($relatedGood->price_old)) { ?>
                                <span class="price old"><?= $relatedGood->price_old ?> р.</span>
                            <?php } ?>
                            <ul class="product-controls-list">
                                <li><a href="#" class="wishlist-add-good" data-id="<?= $relatedGood->id ?>"><span class="icon flaticon-heart68"></span></a></li>
                            </ul>
                        </div>
                    </div>
                <?php } ?>
            </div>
            <!-- product view ajax container -->
            <div class="product-view-ajax-container">
            </div>
            <!-- //end product view ajax container -->
            <!-- Product view compact -->
            <div class="product-view-ajax">
                <div class="layar">
                </div>
                <div class="product-view-container">
                </div>
            </div>
            <!-- //end Product view compact -->
        </div>
        <!-- //end Products list -->
        <div class="clearfix">
        </div>
    </section>
<?php } ?>

views/site/catalog_search.php
<?php
/* @var $this app\components\View */

use yii\widgets\LinkPager;
?>

<section class="col-sm-12 col-md-12 col-lg-12 content-center">
    <h1>Поиск по запросу: <?= $searchText ?></h1>
    <div class="products-list">
        
        <?php if (!empty($catalog)) { ?>
            <?php foreach ($catalog as $item) {
                $categorie = $item->categorie;
                ?>
                <div class="product-preview-outer">
                    <div class="product-preview">
                        <div class="preview-image-outer">
                            <a href="<?= \yii\helpers\Url::to([
                                'site/catalog_element',
                                'catalog_categorie_alias' => $categorie->alias,
                                'catalog_id' => $item->id,
                                'catalog_alias' => $item->alias,
                            ]) ?>" class="preview-image">
                                <?php if (!empty($item->image)) { ?>
                                    <img class="img-responsive img-default" src="<?= $item->getPath('image') ?>" alt="<?= $item->name ?>">
                                <?php } ?>
                            </a>
                        </div>
                        <h3 class="title">
                            <a href="<?= \yii\helpers\Url::to([
                                    'site/catalog_element',
                                    'catalog_categorie_alias' => $categorie->alias,
                                    'catalog_id' => $item->id,
                                    'catalog_alias' => $item->alias,
                                ]) ?>">
                                <?= $item->name ?>
                            </a>
                        </h3>
                        <span class="price new"><?= $item->price ?> р.</span>
                        <?php if (!empty($item->price_old)) { ?>
                            <span class="price old"><?= $item->price_old ?> р.</span>
                        <?php } ?>
                        <ul class="product-controls-list">
                            <li><a href="#"><span class="icon flaticon-heart68"></span></a></li>
                            <li><a href="#drop-shopcart" class='add-to-cart open-cart'><span class="icon flaticon-shopping66"></span></a></li>
                        </ul>
                        <div class="info">
                            <?= $item->content ?>
                        </div>
                        <ul class="product-controls-list-row">
                            <li><a href="#"><span class="icon flaticon-heart68"></span></a></li>
                            <li><a href="#drop-shopcart" class='add-to-cart open-cart'><span class="icon flaticon-shopping66"></span></a></li>
                        </ul>
                    </div>
                </div>
            <?php } ?>
        <?php } else { ?>
            <div class="col-xs-12">
                <div class="alert alert-info fade in">
                    <strong>Список пуст.</strong> Не найдено товаров соответсвующих Вашему запросу
                </div>
            </div>
        <?php } ?>
    </div>
    <!-- Filters -->
    <div class="filters-panel">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <?= LinkPager::widget([
                    'pagination' => $pages,
                    'options' => ['class' => 'paginator pull-right text-right']
                ]) ?>
            </div>
        </div>
    </div>
</section>

views/site/error.php
<?php
/* @var $this app\components\View */
/* @var $exception \yii\web\HttpException|\Exception */
/* @var $handler \yii\web\ErrorHandler */

switch ($exception->statusCode) {
    case 403:
        $this->title = 'Доступ запрещен [ошибка 403]';
        break;
    case 404:
        $this->title = 'Страница не существует [ошибка 404]';
        break;
    case 500:
        $this->title = 'Ошибка сервера [ошибка 500]';
        break;
    default:
        $this->title = $exception->getName() . ' [error ' . $exception->statusCode . ']';
        break;
}

$message = $exception->getMessage();
?>

<h1><?= $this->title ?></h1>
<?php if (empty($message) === false) { ?>
    <p><?= $message ?></p>
<?php } ?>
<ul>
    <li>Вы перешли по ссылке с сайта, на котором была установлена неверная ссылка на наш сайт;</li>
    <li>Вы ошибочно набрали адрес сайта в строке браузера;</li>
    <li>Страница, которую Вы хотели посетить, была удалена или переименована.</li>
</ul>
<a href="/">Вернуться на главную страницу </a>

views/site/gallery.php
<?php
/* @var $this app\components\View */

use yii\widgets\LinkPager;
use yii\helpers\Url;
use app\assets\AppAsset;
?>
<div class="container">
    <div class="subtitle">
        <div>
            <span><?= $this->h1 ?></span>
        </div>
    </div>
</div>
<div class="images-gallery three-columns">
    <div class="images-nospace">
        <?php if (!empty($gallerys)) {
            foreach ($gallerys as $gallery) { ?>
                <div class="image-thumbnail">
                    <a href="<?= Url::to(['site/gallery_element', 'gallery_categorie_id' => $gallery->id]) ?>">
                        <?php if (!empty($gallery->image)) { ?>
                            <img src="<?= $gallery->getPath('image') ?>" alt="<?= $gallery->name ?>">
                        <?php } else { ?>
                            <img src="<?= AppAsset::path('images/gallery/gallery-thumbnail-three-01.jpg') ?>">
                        <?php } ?>
                        <div class="hover"></div>
                    </a>
                </div>
            <?php
            }
        } else { ?>
            <div class="alert alert-info fade in">
                <strong>Список пуст</strong>
            </div>
        <?php } ?>
    </div>
</div>
<div class="container">
    <div class="text-center">
        <?= LinkPager::widget([
            'pagination' => $pages,
            'options' => ['class' => 'paginator']
        ]) ?>
    </div>
</div>

views/site/gallery_element.php
<?php
/* @var $this app\components\View */
?>
<div class="container">
    <div class="subtitle">
        <div>
            <span><?= $this->h1 ?></span>
        </div>
    </div>
</div>
<div class="images-gallery three-columns">
    <div class="images-nospace">
        <?php if (!empty($gallery)) {
            foreach ($gallery as $img) { ?>
                <div class="image-thumbnail">
                    <a href="<?= $img->getPath('image') ?>" class="gallery-group">
                        <?php if (!empty($img->image)) { ?>
                            <img src="<?= $img->getPath('image') ?>" alt="<?= $img->name ?>">
                        <?php } else { ?>
                            <img src="<?= ShopCoolBabyAsset::path('images/gallery/gallery-thumbnail-three-01.jpg') ?>">
                        <?php } ?>
                        <div class="hover"></div>
                    </a>
                </div>
            <?php
            }
        } else { ?>
            <div class="alert alert-info fade in">
                <strong>Список пуст</strong>
            </div>
        <?php } ?>
    </div>
</div>

views/site/index.php
<?= $this->tree->getContent() ?>
<?use app\components\IcmsHelper; ?>
<?// print_r($ABS); ?>
<?// print_r($cont); ?>
<?php foreach ($cont as $content) { ?>

<div class="post-item">
    <div class="data-post"><?= IcmsHelper::dateTimeFormat('d/m <br> Y', $content->g_date) ?></div>
    <img src="<?= $content->getPath('image') ?>" alt="<?=$content->name?>">
    <a href="<?= yii\helpers\Url::to(['site/news_element', 'alias' => $content->alias]) ?>" class="post-link">
        <p><?= $content->anons ?></p>
        <hr class="line-end">
    </a>
</div>

<?php } ?>


































<!--<div class="site-index">-->
<!--    <div class="headline"><h1>--><?//= $this->h1 ?><!--</h1></div>-->
<!---->
<!---->
<!--    <div class="body-content">-->
<!---->
<!--        <div class="row">-->
<!--            <div class="col-lg-12">-->
<!--                --><?//= $this->tree->getContent() ?>
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

views/site/news.php
<?php
use yii\widgets\LinkPager;
use app\components\IcmsHelper;
?>

    <?php if (!empty($contents)) { ?>
        <div>
            <?= $this->tree->getContent() ?>
        </div>

        <?php foreach ($contents as $cont) { ?>

            <div class="post-item">
                <div class="data-post"><?= IcmsHelper::dateTimeFormat('d/m <br> Y', $cont->g_date) ?></div>
                <img src="<?= $cont->getPath('image') ?>" alt="<?=$cont->name?>">
                <a href="<?= yii\helpers\Url::to(['site/news_element', 'alias' => $cont->alias]) ?>" class="post-link">
                    <p class="title"><?= $cont->name ?></p>
                    <p><?= $cont->anons ?></p>
                    <hr class="line-end">
                </a>
            </div>

        <?php } ?>
        <?= LinkPager::widget([
            'pagination' => $pages,
        ]);
    } else { ?>
        <div class="alert alert-info fade in">
            <strong>Список новостей пуст</strong>
        </div>
    <?php } ?>
<?php

views/site/news_element.php
<?php
/* @var $this app\components\View */
?>
<div class="subtitle">
    <div>
        <span><?= $content->name ?></span>
    </div>
</div>
<p><?= date('H:i d.m.Y',strtotime($content->g_date)) ?></p>
<?= $content->content ?>

views/site/textpage.php
<?= $this->tree->getContent() ?>